version: "3.8"

services:
  yolo:
    container_name: yolo_botSort_joshua
    image: humansignal/yolo_botsort_joshua:v0
    build:
      context: .
      args:
        TEST_ENV: ${TEST_ENV}
    mem_limit: 32g
    shm_size: '1g'
    cpus: 4.0
    environment:
      - NVIDIA_VISIBLE_DEVICES=0 # allocate GPU 0 and 1 only
      # specify these parameters if you want to use basic auth for the model server
      - BASIC_AUTH_USER=
      - BASIC_AUTH_PASS=
      # set the log level for the model server
      - LOG_LEVEL=INFO
      # any other parameters that you want to pass to the model server
      - ANY=PARAMETER
      # specify the number of workers and threads for the model server
      - WORKERS=1
      - THREADS=2
      # specify the model directory (likely you don't need to change this)
      - MODEL_DIR=/data/models
      - PYTHONPATH=/app

      # Specify the Label Studio URL and API key to access
      # uploaded, local storage and cloud storage files.
      # Do not use 'localhost' or '127.0.0.1' as it does not work within Docker containers.
      # Use prefix 'http://' or 'https://' for the URL always.
      # Determine the actual IP using 'ifconfig' (Linux/Mac) or 'ipconfig' (Windows).
      # or you can try http://host.docker.internal:<label-studio-port> if you run LS on the same machine
      - LABEL_STUDIO_HOST=https://app.heartex.com
      - LABEL_STUDIO_URL=https://app.heartex.com
      - LABEL_STUDIO_API_KEY=${LABEL_STUDIO_API_KEY}

      # YOLO parameters

      # Allow to use custom `model_path` in labeling configurations
      - ALLOW_CUSTOM_MODEL_PATH=true
      # Show matplotlib debug plot for YOLO predictions
      - DEBUG_PLOT=false
      # Default score threshold, which is used to filter out low-confidence predictions,
      # you can change it in the labeling configuration using `model_score_threshold` parameter in the control tags
      - MODEL_SCORE_THRESHOLD=0.5
      # Model root directory, where the YOLO model files are stored
      - MODEL_ROOT=/app/models
    extra_hosts:
      - "host.docker.internal:host-gateway" # for macos and unix      
    ports:
      - "9091:9090"
    volumes:
      - .:/app
      - ./data/server:/data

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
